---
- hosts: secondary
  remote_user:
  become_method: sudo
  become: true
  vars_files:
    - vars.yaml
  tasks:
    - name: Configure GitLab Runner (using provided token)
      copy:
        dest: /etc/gitlab-runner/config.toml
        content: |
          [[runners]]
            name = "my-podman-runner"
            url = "https://gitlab.example.com"
            token = "your-token"
            executor = "docker"
            [runners.docker]
              host = "unix:///run/podman/podman.sock"
              tls_verify = false
          [session_server]
               listen_address = "0.0.0.0:3000"
    - name: Restart GitLab Runner service
      service:
        name: gitlab-runner
        state: restarted
        
